# Generated by Django 5.1.2 on 2024-11-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costfile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencefile',
            name='column_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referencefile',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
