# Generated by Django 5.1.2 on 2024-11-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costfile_app', '0002_referencefile_column_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audienceforecastconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='referencefile',
            name='column_mapping',
        ),
        migrations.RemoveField(
            model_name='referencefile',
            name='sheet_name',
        ),
    ]
