# Generated by Django 5.1.2 on 2024-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costfile_app', '0005_alter_channel_name_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='cnt_name_grp',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='network_name',
            new_name='provider',
        ),
        migrations.AddField(
            model_name='contract',
            name='allocation',
            field=models.CharField(default='unspecified', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='checktype',
            field=models.CharField(default='unspecified', max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='varf',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='audienceforecastconfig',
            name='end_date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='audienceforecastconfig',
            name='start_date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='business_model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='referencefile',
            name='file_type',
            field=models.CharField(choices=[('audience', 'Audience File'), ('cost', 'Cost File'), ('channel', 'Channel Grouping File'), ('product', 'Product Grouping File'), ('contract', 'Contracts File')], max_length=50),
        ),
    ]
